# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        MainWindow.setMinimumSize(QtCore.QSize(800, 800))
        MainWindow.setMaximumSize(QtCore.QSize(800, 800))
        MainWindow.setStyleSheet("QWidget{\n"
"background-color: rgb(40, 44, 75);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Pages = QtWidgets.QStackedWidget(self.centralwidget)
        self.Pages.setGeometry(QtCore.QRect(-1, 80, 801, 641))
        self.Pages.setObjectName("Pages")
        self.Acceuil = QtWidgets.QWidget()
        self.Acceuil.setObjectName("Acceuil")
        self.bouton_commencer = QtWidgets.QPushButton(self.Acceuil)
        self.bouton_commencer.setGeometry(QtCore.QRect(530, 450, 191, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bouton_commencer.setFont(font)
        self.bouton_commencer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bouton_commencer.setStyleSheet("QPushButton{\n"
"color: rgb(95, 105, 179);\n"
"    background-color: rgb(55, 61, 104);\n"
"selection-background-color: rgb(92, 102, 173);\n"
"border-radius: 10px\n"
"}")
        self.bouton_commencer.setObjectName("bouton_commencer")
        self.instruction = QtWidgets.QLabel(self.Acceuil)
        self.instruction.setGeometry(QtCore.QRect(20, 370, 481, 231))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.instruction.setFont(font)
        self.instruction.setStyleSheet("QLabel{\n"
"color: rgb(112, 125, 211);\n"
"}")
        self.instruction.setAlignment(QtCore.Qt.AlignCenter)
        self.instruction.setWordWrap(True)
        self.instruction.setObjectName("instruction")
        self.instruction_4 = QtWidgets.QLabel(self.Acceuil)
        self.instruction_4.setGeometry(QtCore.QRect(140, 50, 481, 231))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.instruction_4.setFont(font)
        self.instruction_4.setStyleSheet("QLabel{\n"
"color: rgb(112, 125, 211);\n"
"}")
        self.instruction_4.setAlignment(QtCore.Qt.AlignCenter)
        self.instruction_4.setWordWrap(True)
        self.instruction_4.setObjectName("instruction_4")
        self.Pages.addWidget(self.Acceuil)
        self.Importation = QtWidgets.QWidget()
        self.Importation.setObjectName("Importation")
        self.text_chemin = QtWidgets.QLineEdit(self.Importation)
        self.text_chemin.setGeometry(QtCore.QRect(20, 280, 451, 22))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.text_chemin.setFont(font)
        self.text_chemin.setStyleSheet("color: rgb(125, 140, 236);\n"
"background-color: rgb(27, 30, 52);\n"
"border-color: rgb(48, 54, 93);\n"
"border-radius: 15px")
        self.text_chemin.setObjectName("text_chemin")
        self.label = QtWidgets.QLabel(self.Importation)
        self.label.setGeometry(QtCore.QRect(14, 5, 771, 201))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(110, 123, 208);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.bouton_analyser = QtWidgets.QPushButton(self.Importation)
        self.bouton_analyser.setGeometry(QtCore.QRect(490, 380, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bouton_analyser.setFont(font)
        self.bouton_analyser.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bouton_analyser.setStyleSheet("QPushButton{\n"
"color: rgb(95, 105, 179);\n"
"    background-color: rgb(55, 61, 104);\n"
"selection-background-color: rgb(92, 102, 173);\n"
"border-radius: 10px\n"
"}")
        self.bouton_analyser.setObjectName("bouton_analyser")
        self.bouton_parcourir = QtWidgets.QPushButton(self.Importation)
        self.bouton_parcourir.setGeometry(QtCore.QRect(490, 260, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bouton_parcourir.setFont(font)
        self.bouton_parcourir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bouton_parcourir.setStyleSheet("QPushButton{\n"
"color: rgb(95, 105, 179);\n"
"    background-color: rgb(55, 61, 104);\n"
"selection-background-color: rgb(92, 102, 173);\n"
"border-radius: 10px\n"
"}")
        self.bouton_parcourir.setObjectName("bouton_parcourir")
        self.texte_erreur_fichier = QtWidgets.QLabel(self.Importation)
        self.texte_erreur_fichier.setGeometry(QtCore.QRect(30, 340, 431, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.texte_erreur_fichier.setFont(font)
        self.texte_erreur_fichier.setStyleSheet("color: rgb(255, 0, 0);")
        self.texte_erreur_fichier.setText("")
        self.texte_erreur_fichier.setAlignment(QtCore.Qt.AlignCenter)
        self.texte_erreur_fichier.setWordWrap(True)
        self.texte_erreur_fichier.setObjectName("texte_erreur_fichier")
        self.instruction_5 = QtWidgets.QLabel(self.Importation)
        self.instruction_5.setGeometry(QtCore.QRect(30, 480, 751, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.instruction_5.setFont(font)
        self.instruction_5.setStyleSheet("QLabel{\n"
"color: rgb(112, 125, 211);\n"
"}")
        self.instruction_5.setAlignment(QtCore.Qt.AlignCenter)
        self.instruction_5.setWordWrap(True)
        self.instruction_5.setObjectName("instruction_5")
        self.Pages.addWidget(self.Importation)
        self.Erreur = QtWidgets.QWidget()
        self.Erreur.setObjectName("Erreur")
        self.instruction_3 = QtWidgets.QLabel(self.Erreur)
        self.instruction_3.setGeometry(QtCore.QRect(20, 10, 761, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.instruction_3.setFont(font)
        self.instruction_3.setStyleSheet("QLabel{\n"
"color: rgb(112, 125, 211);\n"
"}")
        self.instruction_3.setAlignment(QtCore.Qt.AlignCenter)
        self.instruction_3.setWordWrap(True)
        self.instruction_3.setObjectName("instruction_3")
        self.text_erreur = QtWidgets.QTextBrowser(self.Erreur)
        self.text_erreur.setGeometry(QtCore.QRect(15, 140, 771, 431))
        self.text_erreur.setStyleSheet("background-color: rgb(136, 150, 255);\n"
"color: rgb(8, 8, 15);")
        self.text_erreur.setObjectName("text_erreur")
        self.bouton_retour_erreur = QtWidgets.QPushButton(self.Erreur)
        self.bouton_retour_erreur.setGeometry(QtCore.QRect(10, 580, 781, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bouton_retour_erreur.setFont(font)
        self.bouton_retour_erreur.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bouton_retour_erreur.setStyleSheet("QPushButton{\n"
"color: rgb(95, 105, 179);\n"
"    background-color: rgb(55, 61, 104);\n"
"selection-background-color: rgb(92, 102, 173);\n"
"border-radius: 10px\n"
"}")
        self.bouton_retour_erreur.setObjectName("bouton_retour_erreur")
        self.Pages.addWidget(self.Erreur)
        self.Trame = QtWidgets.QWidget()
        self.Trame.setObjectName("Trame")
        self.liste_trames = QtWidgets.QListWidget(self.Trame)
        self.liste_trames.setGeometry(QtCore.QRect(20, 10, 331, 621))
        self.liste_trames.setStyleSheet("color: rgb(126, 141, 238);")
        self.liste_trames.setObjectName("liste_trames")
        self.bouton_developper = QtWidgets.QPushButton(self.Trame)
        self.bouton_developper.setGeometry(QtCore.QRect(660, 510, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bouton_developper.setFont(font)
        self.bouton_developper.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bouton_developper.setStyleSheet("QPushButton{\n"
"color: rgb(95, 105, 179);\n"
"    background-color: rgb(55, 61, 104);\n"
"selection-background-color: rgb(92, 102, 173);\n"
"border-radius: 10px\n"
"}")
        self.bouton_developper.setObjectName("bouton_developper")
        self.bouton_retour_trame = QtWidgets.QPushButton(self.Trame)
        self.bouton_retour_trame.setGeometry(QtCore.QRect(370, 510, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bouton_retour_trame.setFont(font)
        self.bouton_retour_trame.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bouton_retour_trame.setStyleSheet("QPushButton{\n"
"color: rgb(95, 105, 179);\n"
"    background-color: rgb(55, 61, 104);\n"
"selection-background-color: rgb(92, 102, 173);\n"
"border-radius: 10px\n"
"}")
        self.bouton_retour_trame.setObjectName("bouton_retour_trame")
        self.instruction_2 = QtWidgets.QLabel(self.Trame)
        self.instruction_2.setGeometry(QtCore.QRect(380, 20, 401, 271))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.instruction_2.setFont(font)
        self.instruction_2.setStyleSheet("QLabel{\n"
"color: rgb(112, 125, 211);\n"
"}")
        self.instruction_2.setAlignment(QtCore.Qt.AlignCenter)
        self.instruction_2.setWordWrap(True)
        self.instruction_2.setObjectName("instruction_2")
        self.text_chemin_trame = QtWidgets.QLineEdit(self.Trame)
        self.text_chemin_trame.setGeometry(QtCore.QRect(370, 380, 411, 22))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.text_chemin_trame.setFont(font)
        self.text_chemin_trame.setStyleSheet("color: rgb(125, 140, 236);\n"
"background-color: rgb(27, 30, 52);\n"
"border-color: rgb(48, 54, 93);\n"
"border-radius: 15px")
        self.text_chemin_trame.setObjectName("text_chemin_trame")
        self.texte_erreur_trame = QtWidgets.QLabel(self.Trame)
        self.texte_erreur_trame.setGeometry(QtCore.QRect(370, 440, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.texte_erreur_trame.setFont(font)
        self.texte_erreur_trame.setStyleSheet("color: rgb(255, 0, 0);")
        self.texte_erreur_trame.setText("")
        self.texte_erreur_trame.setAlignment(QtCore.Qt.AlignCenter)
        self.texte_erreur_trame.setObjectName("texte_erreur_trame")
        self.Pages.addWidget(self.Trame)
        self.Analyse = QtWidgets.QWidget()
        self.Analyse.setObjectName("Analyse")
        self.table_trame = QtWidgets.QTableWidget(self.Analyse)
        self.table_trame.setGeometry(QtCore.QRect(20, 0, 761, 71))
        self.table_trame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.table_trame.setAutoFillBackground(False)
        self.table_trame.setStyleSheet("color: rgb(135, 151, 255);\n"
"gridline-color: rgb(72, 80, 136);")
        self.table_trame.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_trame.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_trame.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_trame.setTabKeyNavigation(False)
        self.table_trame.setProperty("showDropIndicator", False)
        self.table_trame.setDragDropOverwriteMode(False)
        self.table_trame.setShowGrid(True)
        self.table_trame.setGridStyle(QtCore.Qt.SolidLine)
        self.table_trame.setCornerButtonEnabled(False)
        self.table_trame.setRowCount(2)
        self.table_trame.setColumnCount(3)
        self.table_trame.setObjectName("table_trame")
        self.table_trame.horizontalHeader().setVisible(False)
        self.table_trame.horizontalHeader().setCascadingSectionResizes(False)
        self.table_trame.horizontalHeader().setDefaultSectionSize(255)
        self.table_trame.horizontalHeader().setMinimumSectionSize(255)
        self.table_trame.verticalHeader().setVisible(False)
        self.table_trame.verticalHeader().setDefaultSectionSize(35)
        self.table_trame.verticalHeader().setMinimumSectionSize(35)
        self.arbre_trame = QtWidgets.QTreeWidget(self.Analyse)
        self.arbre_trame.setGeometry(QtCore.QRect(20, 100, 771, 471))
        self.arbre_trame.setStyleSheet("QHeaderView::section { \n"
"    color: rgb(95, 105, 179);\n"
"    background-color: rgb(55, 61, 104);\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QTreeView{\n"
"color: rgb(134, 150, 254);\n"
"    background-color: rgb(31, 34, 59);\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings {\n"
"        border-image: none;\n"
"        image: url(:/img/branch-closed.png);\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings  {\n"
"        border-image: none;\n"
"image: url(:/img/branch-open.png)\n"
"}\n"
"\n"
"\n"
"")
        self.arbre_trame.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.arbre_trame.setObjectName("arbre_trame")
        self.arbre_trame.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.arbre_trame.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.arbre_trame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setBackground(0, brush)
        item_0 = QtWidgets.QTreeWidgetItem(self.arbre_trame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.arbre_trame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.arbre_trame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        self.arbre_trame.header().setVisible(True)
        self.arbre_trame.header().setDefaultSectionSize(0)
        self.arbre_trame.header().setMinimumSectionSize(0)
        self.bouton_retour_analyse = QtWidgets.QPushButton(self.Analyse)
        self.bouton_retour_analyse.setGeometry(QtCore.QRect(20, 580, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bouton_retour_analyse.setFont(font)
        self.bouton_retour_analyse.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bouton_retour_analyse.setStyleSheet("QPushButton{\n"
"color: rgb(95, 105, 179);\n"
"    background-color: rgb(55, 61, 104);\n"
"selection-background-color: rgb(92, 102, 173);\n"
"border-radius: 10px\n"
"}")
        self.bouton_retour_analyse.setObjectName("bouton_retour_analyse")
        self.bouton_enregistrer = QtWidgets.QPushButton(self.Analyse)
        self.bouton_enregistrer.setGeometry(QtCore.QRect(470, 580, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bouton_enregistrer.setFont(font)
        self.bouton_enregistrer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bouton_enregistrer.setStyleSheet("QPushButton{\n"
"color: rgb(95, 105, 179);\n"
"    background-color: rgb(55, 61, 104);\n"
"selection-background-color: rgb(92, 102, 173);\n"
"border-radius: 10px\n"
"}")
        self.bouton_enregistrer.setObjectName("bouton_enregistrer")
        self.Pages.addWidget(self.Analyse)
        self.menu = QtWidgets.QWidget(self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(9, 0, 791, 71))
        self.menu.setObjectName("menu")
        self.Titre = QtWidgets.QLabel(self.menu)
        self.Titre.setGeometry(QtCore.QRect(-30, 10, 801, 61))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.Titre.setFont(font)
        self.Titre.setStyleSheet("QLabel{\n"
"color: rgb(95, 105, 179);\n"
"}")
        self.Titre.setScaledContents(True)
        self.Titre.setAlignment(QtCore.Qt.AlignCenter)
        self.Titre.setObjectName("Titre")
        self.bouton_acceuil = QtWidgets.QPushButton(self.menu)
        self.bouton_acceuil.setGeometry(QtCore.QRect(0, 10, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bouton_acceuil.setFont(font)
        self.bouton_acceuil.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bouton_acceuil.setStyleSheet("QPushButton{\n"
"color: rgb(95, 105, 179);\n"
"    background-color: rgb(55, 61, 104);\n"
"selection-background-color: rgb(92, 102, 173);\n"
"border-radius: 10px\n"
"}")
        self.bouton_acceuil.setObjectName("bouton_acceuil")
        self.bouton_fermer = QtWidgets.QPushButton(self.menu)
        self.bouton_fermer.setGeometry(QtCore.QRect(660, 10, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bouton_fermer.setFont(font)
        self.bouton_fermer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bouton_fermer.setStyleSheet("QPushButton{\n"
"color: rgb(95, 105, 179);\n"
"    background-color: rgb(55, 61, 104);\n"
"selection-background-color: rgb(92, 102, 173);\n"
"border-radius: 10px\n"
"}")
        self.bouton_fermer.setObjectName("bouton_fermer")
        self.bouton_reduire = QtWidgets.QPushButton(self.menu)
        self.bouton_reduire.setGeometry(QtCore.QRect(530, 10, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bouton_reduire.setFont(font)
        self.bouton_reduire.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bouton_reduire.setStyleSheet("QPushButton{\n"
"color: rgb(95, 105, 179);\n"
"    background-color: rgb(55, 61, 104);\n"
"selection-background-color: rgb(92, 102, 173);\n"
"border-radius: 10px\n"
"}")
        self.bouton_reduire.setObjectName("bouton_reduire")
        self.Logo = QtWidgets.QGraphicsView(self.menu)
        self.Logo.setGeometry(QtCore.QRect(160, 10, 61, 61))
        self.Logo.setStyleSheet("border-image: url(:/img/lg.ico) 0 0 0 0 stretch stretch;")
        self.Logo.setObjectName("Logo")
        self.bas = QtWidgets.QWidget(self.centralwidget)
        self.bas.setGeometry(QtCore.QRect(-1, 730, 801, 61))
        self.bas.setObjectName("bas")
        self.credit = QtWidgets.QLabel(self.bas)
        self.credit.setGeometry(QtCore.QRect(4, 5, 351, 51))
        self.credit.setStyleSheet("QLabel{\n"
"color: rgb(86, 96, 162);\n"
"}")
        self.credit.setObjectName("credit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bouton_commencer.setText(_translate("MainWindow", "Commencer"))
        self.instruction.setText(_translate("MainWindow", "Bienvenue sur Analyseur Donnee Reseaux !\n"
" Ce logiciel vous permettra d\'analyser une trame contenant Ethernet II, IPV4, TCP et HTTP1\n"
"Vous n\'avez qu\'à suivre les instructions !"))
        self.instruction_4.setText(_translate("MainWindow", "- Projet L3 Reseaux [LU3IN33] -\n"
"\n"
"Analyseur de protocole reseau \"Offline\""))
        self.label.setText(_translate("MainWindow", "Importation de la trame en .txt"))
        self.bouton_analyser.setText(_translate("MainWindow", "Analyser"))
        self.bouton_parcourir.setText(_translate("MainWindow", "Parcourir"))
        self.instruction_5.setText(_translate("MainWindow", "Naviguez vers votre fichier et importez le dans ADR-Pro"))
        self.instruction_3.setText(_translate("MainWindow", "Erreur :(\n"
"\n"
"Une erreur s\'est produite pendant l\'analyse de votre trame. Veuillez trouvez plus de détails ci-dessous !"))
        self.text_erreur.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">erreur...</p></body></html>"))
        self.bouton_retour_erreur.setText(_translate("MainWindow", "Retour"))
        self.bouton_developper.setText(_translate("MainWindow", "Développer"))
        self.bouton_retour_trame.setText(_translate("MainWindow", "Retour"))
        self.instruction_2.setText(_translate("MainWindow", "Selectionner une trame et cliquer sur Développer\n"
"\n"
"Vous avez choisis le mauvais fichier ? Pas de problème cliquez sur Retour !"))
        self.arbre_trame.headerItem().setText(0, _translate("MainWindow", "Analyse de la trame"))
        __sortingEnabled = self.arbre_trame.isSortingEnabled()
        self.arbre_trame.setSortingEnabled(False)
        self.arbre_trame.topLevelItem(0).setText(0, _translate("MainWindow", "Ethernet II"))
        self.arbre_trame.topLevelItem(1).setText(0, _translate("MainWindow", "Internet Protocol V4"))
        self.arbre_trame.topLevelItem(2).setText(0, _translate("MainWindow", "Transmission Control Protocol"))
        self.arbre_trame.topLevelItem(3).setText(0, _translate("MainWindow", "HyperText Transfer Protocol"))
        self.arbre_trame.setSortingEnabled(__sortingEnabled)
        self.bouton_retour_analyse.setText(_translate("MainWindow", "Retour"))
        self.bouton_enregistrer.setText(_translate("MainWindow", "Enregistrer"))
        self.Titre.setText(_translate("MainWindow", "ADR-Pro"))
        self.bouton_acceuil.setText(_translate("MainWindow", "Acceuil"))
        self.bouton_fermer.setText(_translate("MainWindow", "X"))
        self.bouton_reduire.setText(_translate("MainWindow", "-"))
        self.credit.setText(_translate("MainWindow", "Projet - RESEAUX - THURAIRAJAH - ABITBOL"))
import gui.ressource_rc
