# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splash_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 800)
        MainWindow.setMinimumSize(QtCore.QSize(600, 800))
        MainWindow.setMaximumSize(QtCore.QSize(600, 825))
        MainWindow.setStyleSheet("QWidget{\n"
"background-color: rgb(40, 44, 75);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(600, 800))
        self.centralwidget.setMaximumSize(QtCore.QSize(600, 800))
        self.centralwidget.setObjectName("centralwidget")
        self.Titre = QtWidgets.QLabel(self.centralwidget)
        self.Titre.setGeometry(QtCore.QRect(0, 10, 621, 261))
        self.Titre.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setPointSize(59)
        font.setBold(False)
        font.setWeight(50)
        self.Titre.setFont(font)
        self.Titre.setStyleSheet("QLabel{\n"
"color: rgb(255, 120, 200);\n"
"}")
        self.Titre.setScaledContents(True)
        self.Titre.setAlignment(QtCore.Qt.AlignCenter)
        self.Titre.setObjectName("Titre")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(17, 450, 561, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background-color : rgb(50, 54, 85);\n"
"    color: rgb(95, 105, 179);\n"
"    border-style : none;\n"
"    border-radius : 10px;\n"
"    text-align : center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    border-radius : 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.596, x2:0.995025, y2:0.591, stop:0.0447761 rgba(255, 120, 200, 255), stop:1 rgba(50, 54, 85, 255));\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.Titre_2 = QtWidgets.QLabel(self.centralwidget)
        self.Titre_2.setGeometry(QtCore.QRect(0, 280, 601, 61))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.Titre_2.setFont(font)
        self.Titre_2.setStyleSheet("QLabel{\n"
"color: rgb(95, 105, 179);\n"
"}")
        self.Titre_2.setScaledContents(True)
        self.Titre_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Titre_2.setObjectName("Titre_2")
        self.credit = QtWidgets.QLabel(self.centralwidget)
        self.credit.setGeometry(QtCore.QRect(0, 740, 601, 51))
        self.credit.setStyleSheet("QLabel{\n"
"color: rgb(86, 96, 162);\n"
"}")
        self.credit.setAlignment(QtCore.Qt.AlignCenter)
        self.credit.setObjectName("credit")
        self.Titre_3 = QtWidgets.QLabel(self.centralwidget)
        self.Titre_3.setGeometry(QtCore.QRect(0, 490, 591, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.Titre_3.setFont(font)
        self.Titre_3.setStyleSheet("QLabel{\n"
"color: rgb(95, 105, 179);\n"
"}")
        self.Titre_3.setScaledContents(True)
        self.Titre_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Titre_3.setObjectName("Titre_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Titre.setText(_translate("MainWindow", "ADR-Pro"))
        self.Titre_2.setText(_translate("MainWindow", "Analyseur de Protocoles Réseau ‘Offline’"))
        self.credit.setText(_translate("MainWindow", "Projet - RESEAUX - THURAIRAJAH - ABITBOL"))
        self.Titre_3.setText(_translate("MainWindow", "Chargement..."))
